language: java
matrix:
  include:
  - jdk: openjdk8
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: oraclejdk10
  - jdk: openjdk10
install: mvn install -Dgpg.skip

after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report
